#!/bin/bash

DB_USER=jwt
DB_PWD=springboot2
DB_NAME=springboot2
DB_NAME_TEST="$DB_NAME"_test

sudo su - postgres -c psql <<EOF
CREATE DATABASE $DB_NAME;
CREATE USER $DB_USER WITH PASSWORD '$DB_PWD';
ALTER ROLE $DB_USER SET client_encoding TO 'utf8';
ALTER ROLE $DB_USER SET default_transaction_isolation TO 'read committed';
ALTER ROLE $DB_USER SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
ALTER USER $DB_USER CREATEDB;
EOF

sudo su - postgres -c psql <<EOF
CREATE DATABASE $DB_NAME_TEST;
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME_TEST TO $DB_USER;
ALTER USER $DB_USER CREATEDB;
EOF